version: '3.9'

# Menyertakan seluruh konfigurasi docker-compose mandiri
include:
  - path: ./sso-be/docker-compose.yml
  - path: ./Farmease-BE/docker-compose.yml
  - path: ./kebun-be/docker-compose.yml
