CREATE TABLE IF NOT EXISTS master.sheep_types (
    id_type SERIAL PRIMARY KEY,
    type_name VARCHAR(100) NOT NULL,
    type_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
